### ISSUE TITLE
Better Event exception reporting

### ISSUE THREAD

**Issue by erocs** [Civcraft/Citadel#107]
Citadel just started spamming this stack which is absolutely worthless. It needs better exception reporting at the top level of all event handlers to debug these better.

2015-06-13 18:58:23 [ERROR] Could not pass event BlockBreakEvent to Citadel v3.2.9
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:305) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.PlayerInteractManager.breakBlock(PlayerInteractManager.java:286) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.PlayerInteractManager.a(PlayerInteractManager.java:189) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.PlayerConnection.a(PlayerConnection.java:604) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.PacketPlayInBlockDig.a(SourceFile:40) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.PacketPlayInBlockDig.a(SourceFile:10) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_45-internal]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_45-internal]
        at net.minecraft.server.v1_8_R2.SystemUtils.a(SourceFile:60) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.A(MinecraftServer.java:710) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.DedicatedServer.A(DedicatedServer.java:368) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.z(MinecraftServer.java:651) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:554) [spigot.jar:git-Spigot-1d14d5f-7722428]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45-internal]
Caused by: java.lang.NullPointerException

**Comment by ProgrammerDan** [comment]
Is this an error in how bukkit delegates events to Citadel, or a problem with how Citadel receives events? I'm not seeing any Citadel stack frames in the trace, just the final delegation error as reported by Bukkit.

Was there any error before this? Something that might indicate Citadel went offline or stopped accepting events?

**Comment by erocs** [comment]
Citadel's stack wasn't dumped, which is the bug.

**Comment by ProgrammerDan** [comment]
Ah, got it.

**Comment by rourke750** [comment]
Is this the whole stack trace?

**Comment by erocs** [comment]
That's all that was reported.

**Comment by rourke750** [comment]
Is it possible it was just a random spigot bug or is it still happening?

**Comment by erocs** [comment]
It's happened intermittently for years. It's not really a new issue, but
does hide potential bug stacks like in this instance. Usually there's a
good stack that shows up for debugging but this series of exceptions didn't
have one.

**Comment by erocs** [comment]
Lots more exceptions with no way to know what's going bad in Citadel.

**Comment by ProgrammerDan** [comment]
So most of these are caused by a deleted group -- some of the isPermissible and isOwner checks fail catastrophically for "NameLayerSpecial" as it has a null owner. I've added checks and catches in the latest versions of Citadel, Juke, and Namelayer that should give better reporting. Ultimately the fix will be to just delete the reinforcement, that's next on my todo.
