### ISSUE TITLE
Does Citadel setup the db's itself? 

### ISSUE THREAD

**Issue by ttk2** [Civcraft/Citadel#155]
[21:06:58 ERROR]: [Citadel] Could not execute SQL statement!
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'pumpkin.reinforcement_id' doesn't exist
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_72-internal]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_72-internal]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_72-internal]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_72-internal]
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at com.mysql.jdbc.Util.getInstance(Util.java:382) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1052) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2407) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2325) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2310) ~[spigot.jar:git-Spigot-d97e08b-880a532]
        at vg.civcraft.mc.citadel.database.Database.execute(Database.java:113) [Citadel-3.4.0.jar:?]
        at vg.civcraft.mc.citadel.database.CitadelReinforcementData.createTables(CitadelReinforcementData.java:170) [Citadel-3.4.0.jar:?]
        at vg.civcraft.mc.citadel.database.CitadelReinforcementData.<init>(CitadelReinforcementData.java:34) [Citadel-3.4.0.jar:?]
        at vg.civcraft.mc.citadel.Citadel.initializeDatabase(Citadel.java:72) [Citadel-3.4.0.jar:?]
        at vg.civcraft.mc.citadel.Citadel.onEnable(Citadel.java:49) [Citadel-3.4.0.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) [spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot.jar:git-Spigot-d97e08b-880a532]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [spigot.jar:git-Spigot-d97e08b-880a532]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:524) [spigot.jar:git-Spigot-d97e08b-880a532]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72-internal]

**Comment by ProgrammerDan** [comment]
It should, but it uses Namelayer's plugin db version tracking system to determine if it needs to. So if Namelayer already thinks Citadel is updated, it won't do it again.

**Comment by rourke750** [comment]
Yea need to move that over too.
