### ISSUE TITLE
IllegalArgumentException

### ISSUE THREAD

**Issue by erocs** [Civcraft/Citadel#189]
[00:07:43] [pool-14-thread-38/ERROR]: Could not pass event AsyncPluginBroadcastMessageEvent to Citadel v3.5.5
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at vg.civcraft.mc.mercury.events.BukkitEventManager.fireMessage(BukkitEventManager.java:11) [Mercury.jar:?]
        at vg.civcraft.mc.mercury.events.EventManager.fireMessage(EventManager.java:15) [Mercury.jar:?]
        at vg.civcraft.mc.mercury.rabbitmq.RabbitConsumer.handleDelivery(RabbitConsumer.java:83) [Mercury.jar:?]
        at com.rabbitmq.client.impl.ConsumerDispatcher$5.run(ConsumerDispatcher.java:144) [Mercury.jar:?]
        at com.rabbitmq.client.impl.ConsumerWorkService$WorkPoolRunnable.run(ConsumerWorkService.java:99) [Mercury.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_91]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_91]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.ratbutcher
        at java.lang.Enum.valueOf(Enum.java:238) ~[?:1.8.0_91]
        at org.bukkit.Material.valueOf(Material.java:1) ~[spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at vg.civcraft.mc.citadel.listener.ShardListener.messageReceive(ShardListener.java:84) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor20.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-6016ac7-6d3efa0]

**Comment by Maxopoly** [comment]
This is caused by pipes in group names, which fuck up stuff when splitting by the pipe separator we use
