### ISSUE TITLE
NPE BlockListener.onFortificationMode

### ISSUE THREAD

**Issue by erocs** [Civcraft/Citadel#190]
Caused by: java.lang.NullPointerException
        at vg.civcraft.mc.citadel.listener.BlockListener.onFortificationMode(BlockListener.java:146) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor327.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-6016ac7-6d3efa0]

**Comment by Maxopoly** [comment]
https://github.com/Civcraft/Citadel/commit/9da6e361f81650c4c11e0a8a5c74f4f36acb1e70
