### ISSUE TITLE
NPE ShardListener.serverChange

### ISSUE THREAD

**Issue by erocs** [Civcraft/Citadel#191]
[00:28:03] [Server thread/ERROR]: Could not pass event PlayerChangeServerEvent to Citadel v3.5.5
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:310) ~[spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at vg.civcraft.mc.bettershards.BetterShardsPlugin.teleportPlayerToServer(BetterShardsPlugin.java:203) [BetterShardsBukkit.jar:?]
        at vg.civcraft.mc.bettershards.BetterShardsAPI.connectPlayer(BetterShardsAPI.java:69) [BetterShardsBukkit.jar:?]
        at vg.civcraft.mc.bettershards.portal.portals.WorldBorderPortal.teleport(WorldBorderPortal.java:170) [BetterShardsBukkit.jar:?]
        at vg.civcraft.mc.bettershards.listeners.BetterShardsListener.playerMoveEvent(BetterShardsListener.java:204) [BetterShardsBukkit.jar:?]
        at sun.reflect.GeneratedMethodAccessor46.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) [spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) [spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:607) [spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at net.minecraft.server.v1_10_R1.PacketPlayInFlying.a(SourceFile:126) [spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at net.minecraft.server.v1_10_R1.PacketPlayInFlying$PacketPlayInPosition.a(SourceFile:57) [spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_91]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_91]
        at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:733) [spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot.jar:git-Spigot-6016ac7-6d3efa0]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.lang.NullPointerException
        at vg.civcraft.mc.citadel.listener.ShardListener.serverChange(ShardListener.java:40) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor356.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_91]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_91]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[spigot.jar:git-Spigot-6016ac7-6d3efa0]

**Comment by Maxopoly** [comment]
Prevented by https://github.com/Civcraft/Citadel/commit/2041e1243606660e9185edc31e3248dccd1c19c5, the actual cause is #189 though
