### ISSUE TITLE
Exiting boats sometimes causes Citadel error 

### ISSUE THREAD

**Issue by ttk2** [Civcraft/Citadel#42]
2015-01-31 17:43:33 [WARN] com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry '31850225' for key 'PRIMARY'
2015-01-31 17:43:33 [WARN]      at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2015-01-31 17:43:33 [WARN]      at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
2015-01-31 17:43:33 [WARN]      at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2015-01-31 17:43:33 [WARN]      at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
2015-01-31 17:43:33 [WARN]      at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
2015-01-31 17:43:33 [WARN]      at com.mysql.jdbc.Util.getInstance(Util.java:382)
2015-01-31 17:43:33 [WARN]      at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
2015-01-31 17:43:33 [WARN]      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
2015-01-31 17:43:33 [WARN]      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
2015-01-31 17:43:33 [WARN]      at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
2015-01-31 17:43:33 [WARN]      at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
2015-01-31 17:43:33 [WARN]      at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
2015-01-31 17:43:33 [WARN]      at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
2015-01-31 17:43:33 [WARN]      at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1362)
2015-01-31 17:43:33 [WARN]      at vg.civcraft.mc.citadel.database.CitadelReinforcementData.insertReinforcement(CitadelReinforcementData.java:358)
2015-01-31 17:43:33 [WARN]      at vg.civcraft.mc.citadel.ReinforcementManager.saveInitialReinforcement(ReinforcementManager.java:71)
2015-01-31 17:43:33 [WARN]      at vg.civcraft.mc.citadel.Utility.createPlayerReinforcement(Utility.java:123)
2015-01-31 17:43:33 [WARN]      at vg.civcraft.mc.citadel.listener.BlockListener.onFortificationMode(BlockListener.java:108)
2015-01-31 17:43:33 [WARN]      at sun.reflect.GeneratedMethodAccessor206.invoke(Unknown Source)
2015-01-31 17:43:33 [WARN]      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2015-01-31 17:43:33 [WARN]      at java.lang.reflect.Method.invoke(Method.java:606)
2015-01-31 17:43:33 [WARN]      at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298)
2015-01-31 17:43:33 [WARN]      at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
2015-01-31 17:43:33 [WARN]      at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
2015-01-31 17:43:33 [WARN]      at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
2015-01-31 17:43:33 [WARN]      at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:148)
2015-01-31 17:43:33 [WARN]      at net.minecraft.server.v1_7_R4.ItemStack.placeItem(ItemStack.java:139)
2015-01-31 17:43:33 [WARN]      at net.minecraft.server.v1_7_R4.PlayerInteractManager.interact(PlayerInteractManager.java:391)
2015-01-31 17:43:33 [WARN]      at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:662)
2015-01-31 17:43:33 [WARN]      at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.a(SourceFile:60)
2015-01-31 17:43:33 [WARN]      at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.handle(SourceFile:9)
2015-01-31 17:43:33 [WARN]      at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184)
2015-01-31 17:43:33 [WARN]      at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81)
2015-01-31 17:43:33 [WARN]      at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734)
2015-01-31 17:43:33 [WARN]      at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289)
2015-01-31 17:43:33 [WARN]      at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)
2015-01-31 17:43:33 [WARN]      at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)
2015-01-31 17:43:33 [WARN]      at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)

**Comment by ttk2** [comment]
its not boats that causes this one, still getting it every 10-15 minutes or so though

**Comment by jjj5311** [comment]
Rourke your the man, thanks for all of your time
