### ISSUE TITLE
NPE ReinforcementManager.getReinforcement

### ISSUE THREAD

**Issue by erocs** [Civcraft/Citadel#51]
2015-02-01 15:07:41 [WARN] net.minecraft.util.com.google.common.util.concurrent.UncheckedExecutionException: java.lang.NullPointerException
2015-02-01 15:07:41 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2201)
2015-02-01 15:07:41 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache.get(LocalCache.java:3934)
2015-02-01 15:07:41 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
2015-02-01 15:07:41 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
2015-02-01 15:07:41 [WARN]      at vg.civcraft.mc.citadel.ReinforcementManager.getReinforcement(ReinforcementManager.java:82)
2015-02-01 15:07:41 [WARN]      at vg.civcraft.mc.citadel.ReinforcementManager.getReinforcement(ReinforcementManager.java:99)
2015-02-01 15:07:41 [WARN]      at vg.civcraft.mc.citadel.listener.BlockListener.interact(BlockListener.java:397)
2015-02-01 15:07:41 [WARN]      at sun.reflect.GeneratedMethodAccessor110.invoke(Unknown Source)
2015-02-01 15:07:41 [WARN]      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2015-02-01 15:07:41 [WARN]      at java.lang.reflect.Method.invoke(Method.java:606)
2015-02-01 15:07:41 [WARN]      at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298)
2015-02-01 15:07:41 [WARN]      at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
2015-02-01 15:07:41 [WARN]      at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
2015-02-01 15:07:41 [WARN]      at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
2015-02-01 15:07:41 [WARN]      at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:242)
2015-02-01 15:07:41 [WARN]      at net.minecraft.server.v1_7_R4.PlayerInteractManager.interact(PlayerInteractManager.java:375)
2015-02-01 15:07:41 [WARN]      at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:662)
2015-02-01 15:07:41 [WARN]      at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.a(SourceFile:60)
2015-02-01 15:07:41 [WARN]      at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.handle(SourceFile:9)
2015-02-01 15:07:41 [WARN]      at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184)
2015-02-01 15:07:41 [WARN]      at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81)
2015-02-01 15:07:41 [WARN]      at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734)
2015-02-01 15:07:41 [WARN]      at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289)
2015-02-01 15:07:41 [WARN]      at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)
2015-02-01 15:07:41 [WARN]      at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)
2015-02-01 15:07:41 [WARN]      at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)

**Comment by rourke750** [comment]
Does this still happen?

**Comment by ttk2** [comment]
not seeing it
