### ISSUE TITLE
.MySQLIntegrityConstraintViolationException: Column 'group_id' 

### ISSUE THREAD

**Issue by ttk2** [Civcraft/Citadel#52]
2015-02-01 22:53:19 [WARN] com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'group_id' cannot be null                      │··················
2015-02-01 22:53:19 [WARN]      at sun.reflect.GeneratedConstructorAccessor205.newInstance(Unknown Source)                                                   │··················
2015-02-01 22:53:19 [WARN]      at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)                      │··················
2015-02-01 22:53:19 [WARN]      at java.lang.reflect.Constructor.newInstance(Constructor.java:526)                                                           │··················
2015-02-01 22:53:19 [WARN]      at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)                                                                      │··················
2015-02-01 22:53:19 [WARN]      at com.mysql.jdbc.Util.getInstance(Util.java:382)                                                                            │··················
2015-02-01 22:53:19 [WARN]      at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)                                                            │··················
2015-02-01 22:53:19 [WARN]      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)                                                                │··················
2015-02-01 22:53:19 [WARN]      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)                                                                │··················
2015-02-01 22:53:19 [WARN]      at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)                                                                     │··················
2015-02-01 22:53:19 [WARN]      at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)                                                                  │··················
2015-02-01 22:53:19 [WARN]      at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)                                                           │··················
2015-02-01 22:53:19 [WARN]      at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)                                             │··················
2015-02-01 22:53:19 [WARN]      at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1362)                                                     │··················
2015-02-01 22:53:19 [WARN]      at vg.civcraft.mc.citadel.database.CitadelReinforcementData.saveReinforcement(CitadelReinforcementData.java:494)             │··················
2015-02-01 22:53:19 [WARN]      at vg.civcraft.mc.citadel.ReinforcementManager.saveReinforcement(ReinforcementManager.java:61)                               │··················
2015-02-01 22:53:19 [WARN]      at vg.civcraft.mc.citadel.ReinforcementManager$1.onRemoval(ReinforcementManager.java:28)                                     │··················
2015-02-01 22:53:19 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache.processPendingNotifications(LocalCache.java:1954)                   │··················
2015-02-01 22:53:19 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache$Segment.runUnlockedCleanup(LocalCache.java:3457)                    │··················
2015-02-01 22:53:19 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache$Segment.postWriteCleanup(LocalCache.java:3433)                      │··················
2015-02-01 22:53:19 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2271)                       │··················
2015-02-01 22:53:19 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)                                   │··················
2015-02-01 22:53:19 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache.get(LocalCache.java:3934)                                           │··················
2015-02-01 22:53:19 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)                                     │··················
2015-02-01 22:53:19 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)                         │··················
2015-02-01 22:53:19 [WARN]      at vg.civcraft.mc.citadel.ReinforcementManager.getReinforcement(ReinforcementManager.java:82)                                │··················
2015-02-01 22:53:19 [WARN]      at vg.civcraft.mc.citadel.ReinforcementManager.getReinforcement(ReinforcementManager.java:99)                                │··················
2015-02-01 22:53:19 [WARN]      at vg.civcraft.mc.citadel.listener.BlockListener.interact(BlockListener.java:402)                                            │··················
2015-02-01 22:53:19 [WARN]      at sun.reflect.GeneratedMethodAccessor75.invoke(Unknown Source)                                                              │··················
2015-02-01 22:53:19 [WARN]      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                     │··················
2015-02-01 22:53:19 [WARN]      at java.lang.reflect.Method.invoke(Method.java:606)                                                                          │··················
2015-02-01 22:53:19 [WARN]      at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298)                                              │··················
2015-02-01 22:53:19 [WARN]      at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)                                                │··················
2015-02-01 22:53:19 [WARN]      at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)                                             │··················
2015-02-01 22:53:19 [WARN]      at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)                                             │··················
2015-02-01 22:53:19 [WARN]      at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:242)                │··················
2015-02-01 22:53:19 [WARN]      at net.minecraft.server.v1_7_R4.PlayerInteractManager.dig(PlayerInteractManager.java:103)                                    │··················
2015-02-01 22:53:19 [WARN]      at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:552)                                                │··················
2015-02-01 22:53:19 [WARN]      at net.minecraft.server.v1_7_R4.PacketPlayInBlockDig.a(SourceFile:53)                                                        │··················
2015-02-01 22:53:19 [WARN]      at net.minecraft.server.v1_7_R4.PacketPlayInBlockDig.handle(SourceFile:8)            
2015-02-01 22:53:19 [WARN]      at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:552)                                      [222/9547]│··················
2015-02-01 22:53:19 [WARN]      at net.minecraft.server.v1_7_R4.PacketPlayInBlockDig.a(SourceFile:53)                                                        │··················
2015-02-01 22:53:19 [WARN]      at net.minecraft.server.v1_7_R4.PacketPlayInBlockDig.handle(SourceFile:8)                                                    │··················
2015-02-01 22:53:19 [WARN]      at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184)                                                    │··················
2015-02-01 22:53:19 [WARN]      at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81)                                                 │··················
2015-02-01 22:53:19 [WARN]      at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734)                                                  │··················
2015-02-01 22:53:19 [WARN]      at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289)                                                  │··················
2015-02-01 22:53:19 [WARN]      at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)                                                  │··················
2015-02-01 22:53:19 [WARN]      at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)                                                │··················
2015-02-01 22:53:19 [WARN]      at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)

**Comment by rourke750** [comment]
Possibly some reinforcements of null groups from somewhere.  added logging of where.

**Comment by rourke750** [comment]
@erocs @drjawa @ttk2 Are any more of occurring?

**Comment by ttk2** [comment]
not that I have seen, will reopen if I do

**Comment by ttk2** [comment]
just got it again now

2015-02-04 22:45:12 [WARN] com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'group_id' cannot be null                                [48/9993]
2015-02-04 22:45:12 [WARN]      at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2015-02-04 22:45:12 [WARN]      at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
2015-02-04 22:45:12 [WARN]      at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2015-02-04 22:45:12 [WARN]      at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
2015-02-04 22:45:12 [WARN]      at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
2015-02-04 22:45:12 [WARN]      at com.mysql.jdbc.Util.getInstance(Util.java:382)
2015-02-04 22:45:12 [WARN]      at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
2015-02-04 22:45:12 [WARN]      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
2015-02-04 22:45:12 [WARN]      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
2015-02-04 22:45:12 [WARN]      at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
2015-02-04 22:45:12 [WARN]      at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
2015-02-04 22:45:12 [WARN]      at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
2015-02-04 22:45:12 [WARN]      at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
2015-02-04 22:45:12 [WARN]      at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1362)
2015-02-04 22:45:12 [WARN]      at vg.civcraft.mc.citadel.database.CitadelReinforcementData.saveReinforcement(CitadelReinforcementData.java:494)
2015-02-04 22:45:12 [WARN]      at vg.civcraft.mc.citadel.ReinforcementManager.saveReinforcement(ReinforcementManager.java:65)
2015-02-04 22:45:12 [WARN]      at vg.civcraft.mc.citadel.ReinforcementManager$1.onRemoval(ReinforcementManager.java:32)
2015-02-04 22:45:12 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache.processPendingNotifications(LocalCache.java:1954)
2015-02-04 22:45:12 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache$Segment.runUnlockedCleanup(LocalCache.java:3457)
2015-02-04 22:45:12 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache$Segment.postWriteCleanup(LocalCache.java:3433)
2015-02-04 22:45:12 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache$Segment.storeLoadedValue(LocalCache.java:3164)
2015-02-04 22:45:12 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2351)
2015-02-04 22:45:12 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2318)
2015-02-04 22:45:12 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2280)
2015-02-04 22:45:12 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2195)
2015-02-04 22:45:12 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache.get(LocalCache.java:3934)
2015-02-04 22:45:12 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3938)
2015-02-04 22:45:12 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4821)
2015-02-04 22:45:12 [WARN]      at vg.civcraft.mc.citadel.ReinforcementManager.getReinforcement(ReinforcementManager.java:86)
2015-02-04 22:45:12 [WARN]      at vg.civcraft.mc.citadel.ReinforcementManager.getReinforcement(ReinforcementManager.java:105)
2015-02-04 22:45:12 [WARN]      at vg.civcraft.mc.citadel.listener.BlockListener.interact(BlockListener.java:402)
2015-02-04 22:45:12 [WARN]      at sun.reflect.GeneratedMethodAccessor76.invoke(Unknown Source)
2015-02-04 22:45:12 [WARN]      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2015-02-04 22:45:12 [WARN]      at java.lang.reflect.Method.invoke(Method.java:606)
2015-02-04 22:45:12 [WARN]      at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298)
2015-02-04 22:45:12 [WARN]      at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
2015-02-04 22:45:12 [WARN]      at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
2015-02-04 22:45:12 [WARN]      at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
2015-02-04 22:45:12 [WARN]      at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:242)
2015-02-04 22:45:12 [WARN]      at net.minecraft.server.v1_7_R4.PlayerInteractManager.dig(PlayerInteractManager.java:103)
2015-02-04 22:45:12 [WARN]      at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:552)
2015-02-04 22:45:12 [WARN]      at net.minecraft.server.v1_7_R4.PacketPlayInBlockDig.a(SourceFile:53)
2015-02-04 22:45:12 [WARN]      at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289)
2015-02-04 22:45:12 [WARN]      at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:552)                                                           [7/9993]
2015-02-04 22:45:12 [WARN]      at net.minecraft.server.v1_7_R4.PacketPlayInBlockDig.a(SourceFile:53)
2015-02-04 22:45:12 [WARN]      at net.minecraft.server.v1_7_R4.PacketPlayInBlockDig.handle(SourceFile:8)
2015-02-04 22:45:12 [WARN]      at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184)
2015-02-04 22:45:12 [WARN]      at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81)
2015-02-04 22:45:12 [WARN]      at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734)
2015-02-04 22:45:12 [WARN]      at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289)
2015-02-04 22:45:12 [WARN]      at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)
2015-02-04 22:45:12 [WARN]      at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)
2015-02-04 22:45:12 [WARN]      at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)

**Comment by rourke750** [comment]
Right before it there should have been cords.

**Comment by ttk2** [comment]
nope, just normal misc log messages

**Comment by rourke750** [comment]
ah youre not update to version with it.

**Comment by ttk2** [comment]
those verisons still need testing on Civtest
