### ISSUE TITLE
Could not pass event BlockPlaceEvent to Citadel v3.1.7

### ISSUE THREAD

**Issue by ttk2** [Civcraft/Citadel#61]
2015-02-04 16:51:33 [ERROR] Could not pass event BlockPlaceEvent to Citadel v3.1.7                                                                           │··················
org.bukkit.event.EventException                                                                                                                              │··················
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]                     │··················
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]                       │··················
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]                     │··················
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]                     │··················
        at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:148) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02de│··················
c9b]                                                                                                                                                         │··················
        at net.minecraft.server.v1_7_R4.ItemStack.placeItem(ItemStack.java:139) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]                              │··················
        at net.minecraft.server.v1_7_R4.PlayerInteractManager.interact(PlayerInteractManager.java:391) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]       │··················
        at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:662) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]                        │··················
        at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.a(SourceFile:60) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]                              │··················
        at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.handle(SourceFile:9) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]                          │··················
        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]                            │··················
        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]                         │··················
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]                          │··················
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]                          │··················
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]                          │··················
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]                        │··················
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]                          │··················
Caused by: java.util.MissingFormatArgumentException: Format specifier 's'                                                                                    │··················
        at java.util.Formatter.format(Formatter.java:2487) ~[?:1.7.0_75]                                                                                     │··················
        at java.util.Formatter.format(Formatter.java:2423) ~[?:1.7.0_75]                                                                                     │··················
        at java.lang.String.format(String.java:2790) ~[?:1.7.0_75]                                                                                           │··················
        at vg.civcraft.mc.citadel.listener.BlockListener.onFortificationMode(BlockListener.java:111) ~[?:?]                                                  │··················
        at sun.reflect.GeneratedMethodAccessor117.invoke(Unknown Source) ~[?:?]                                                                              │··················
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_75]                                               │··················
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_75]                                                                                    │··················
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]                     │··················
        ... 16 more

**Comment by jjj5311** [comment]
Seems to be cause here, probably a block that returns null for a name?

https://github.com/Civcraft/Citadel/blob/master/src/vg/civcraft/mc/citadel/listener/BlockListener.java#L111

This would add some logging to try and get the block id of the block in question, and not generate the stack trace i think

https://github.com/jjj5311/Citadel/commit/5bba6e450a206421f520e2baed362a480c0ba547

**Comment by spaceFountain** [comment]
I don't think it's the name being null. It shouldn't be able to happen. Unless Block or BlockType is null. as BlockType is a enum and .name just comes from that.

**Comment by jjj5311** [comment]
So you think we can just add a check at the beginning of on BlockPlaceEvent to check if block is null?  Probably need some debugging info to figure how null block or material is getting passed

**Comment by rourke750** [comment]
That code isnt live on the server

**Comment by spaceFountain** [comment]
Right of course. This a49b55c33eff6c4fe83b0b84de823d416bd44f7d fixes it then right? This issue can be closed?

**Comment by drjawa** [comment]
This has been live for awhile, fixed issue I believe, re-open if wrong.
