### ISSUE TITLE
Civtest Citadel Null Group Exception

### ISSUE THREAD

**Issue by drjawa** [Civcraft/Citadel#63]
2015-02-06 03:26:34 [INFO] [Citadel] [Citadel] The Null Group Exception that is being followed has to deal with the group na[294/9400]
 location: -5365, 68, 105, at world: world
2015-02-06 03:26:34 [WARN] com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'group_id' cannot be nul
l
2015-02-06 03:26:34 [WARN]      at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2015-02-06 03:26:34 [WARN]      at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
2015-02-06 03:26:34 [WARN]      at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45
)
2015-02-06 03:26:34 [WARN]      at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
2015-02-06 03:26:34 [WARN]      at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
2015-02-06 03:26:34 [WARN]      at com.mysql.jdbc.Util.getInstance(Util.java:382)
2015-02-06 03:26:34 [WARN]      at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
2015-02-06 03:26:34 [WARN]      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
2015-02-06 03:26:34 [WARN]      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
2015-02-06 03:26:34 [WARN]      at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
2015-02-06 03:26:34 [WARN]      at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
2015-02-06 03:26:34 [WARN]      at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
2015-02-06 03:26:34 [WARN]      at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
2015-02-06 03:26:34 [WARN]      at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1362)
2015-02-06 03:26:34 [WARN]      at vg.civcraft.mc.citadel.database.CitadelReinforcementData.saveReinforcement(CitadelReinforcementData
.java:494)
2015-02-06 03:26:34 [WARN]      at vg.civcraft.mc.citadel.ReinforcementManager.saveReinforcement(ReinforcementManager.java:65)
2015-02-06 03:26:34 [WARN]      at vg.civcraft.mc.citadel.ReinforcementManager$1.onRemoval(ReinforcementManager.java:32)
2015-02-06 03:26:34 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache.processPendingNotifications(LocalCache.java:1
954)
2015-02-06 03:26:34 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache$Segment.runUnlockedCleanup(LocalCache.java:34
57)
2015-02-06 03:26:34 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache$Segment.postWriteCleanup(LocalCache.java:3433
)
2015-02-06 03:26:34 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache$Segment.clear(LocalCache.java:3238)
2015-02-06 03:26:34 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache.clear(LocalCache.java:4204)
2015-02-06 03:26:34 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache$LocalManualCache.invalidateAll(LocalCache.jav
a:4772)
2015-02-06 03:26:34 [WARN]      at vg.civcraft.mc.citadel.ReinforcementManager.invalidateAllReinforcements(ReinforcementManager.java:2015-02-06 03:26:34 [WARN]      at vg.civcraft.mc.citadel.ReinforcementManager.invalidateAllReinforcements(ReinforcementManager.java:1
25)
2015-02-06 03:26:34 [WARN]      at vg.civcraft.mc.citadel.Citadel.onDisable(Citadel.java:59)
2015-02-06 03:26:34 [WARN]      at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:318)
2015-02-06 03:26:34 [WARN]      at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:356)
2015-02-06 03:26:34 [WARN]      at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424)
2015-02-06 03:26:34 [WARN]      at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417)
2015-02-06 03:26:34 [WARN]      at org.bukkit.craftbukkit.v1_7_R4.CraftServer.disablePlugins(CraftServer.java:412)
2015-02-06 03:26:34 [WARN]      at net.minecraft.server.v1_7_R4.MinecraftServer.stop(MinecraftServer.java:393)
2015-02-06 03:26:34 [WARN]      at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:525)
2015-02-06 03:26:34 [WARN]      at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)
2015-02-06 03:26:34 [INFO] [Citadel] [Citadel] The Null Group Exception that is being followed has to deal with the group name: is, at
 location: -5369, 69, 105, at world: world
2015-02-06 03:26:34 [WARN] com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Column 'group_id' cannot be nul
l
2015-02-06 03:26:34 [WARN]      at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2015-02-06 03:26:34 [WARN]      at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
2015-02-06 03:26:34 [WARN]      at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45
)
2015-02-06 03:26:34 [WARN]      at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
2015-02-06 03:26:34 [WARN]      at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
2015-02-06 03:26:34 [WARN]      at com.mysql.jdbc.Util.getInstance(Util.java:382)
2015-02-06 03:26:34 [WARN]      at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
2015-02-06 03:26:34 [WARN]      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
2015-02-06 03:26:34 [WARN]      at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
2015-02-06 03:26:34 [WARN]      at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
2015-02-06 03:26:34 [WARN]      at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
2015-02-06 03:26:34 [WARN]      at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
2015-02-06 03:26:34 [WARN]      at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
2015-02-06 03:26:34 [WARN]      at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1362)
2015-02-06 03:26:34 [WARN]      at vg.civcraft.mc.citadel.database.CitadelReinforcementData.saveReinforcement(CitadelReinforcementDat$
2015-02-06 03:26:34 [WARN]      at vg.civcraft.mc.citadel.ReinforcementManager.saveReinforcement(ReinforcementManager.java:65)
2015-02-06 03:26:34 [WARN]      at vg.civcraft.mc.citadel.ReinforcementManager$1.onRemoval(ReinforcementManager.java:32)
2015-02-06 03:26:34 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache.processPendingNotifications(LocalCache.java:1
954)
2015-02-06 03:26:34 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache$Segment.runUnlockedCleanup(LocalCache.java:34
57)
2015-02-06 03:26:34 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache$Segment.postWriteCleanup(LocalCache.java:3433
)
2015-02-06 03:26:34 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache$Segment.clear(LocalCache.java:3238)
2015-02-06 03:26:34 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache.clear(LocalCache.java:4204)
2015-02-06 03:26:34 [WARN]      at net.minecraft.util.com.google.common.cache.LocalCache$LocalManualCache.invalidateAll(LocalCache.jav
a:4772)
2015-02-06 03:26:34 [WARN]      at vg.civcraft.mc.citadel.ReinforcementManager.invalidateAllReinforcements(ReinforcementManager.java:1
25)
2015-02-06 03:26:34 [WARN]      at vg.civcraft.mc.citadel.Citadel.onDisable(Citadel.java:59)
2015-02-06 03:26:34 [WARN]      at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:318)
2015-02-06 03:26:34 [WARN]      at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:356)
2015-02-06 03:26:34 [WARN]      at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:424)
2015-02-06 03:26:34 [WARN]      at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417)
2015-02-06 03:26:34 [WARN]      at org.bukkit.craftbukkit.v1_7_R4.CraftServer.disablePlugins(CraftServer.java:412)
2015-02-06 03:26:34 [WARN]      at net.minecraft.server.v1_7_R4.MinecraftServer.stop(MinecraftServer.java:393)
2015-02-06 03:26:34 [WARN]      at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:525)
2015-02-06 03:26:34 [WARN]      at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628)

**Comment by rourke750** [comment]
I figured this out working on a fix.
