### ISSUE TITLE
/ctf error null unhandled exception

### ISSUE THREAD

**Issue by drjawa** [Civcraft/Citadel#71]
2015-02-14 19:22:47 [INFO] CENSORED issued server command: /ctf
2015-02-14 19:22:47 [ERROR] null
org.bukkit.command.CommandException: Unhandled exception executing command 'ctf' in plugin Citadel v3.2.3
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:181) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at org.bukkit.craftbukkit.v1_7_R4.CraftServer.dispatchCommand(CraftServer.java:767) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02
dec9b]
        at net.minecraft.server.v1_7_R4.PlayerConnection.handleCommand(PlayerConnection.java:1013) [spigot.jar:git-Spigot-1.7.9-R0.2-2
03-g02dec9b]
        at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:850) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.PacketPlayInChat.a(PacketPlayInChat.java:28) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.PacketPlayInChat.handle(PacketPlayInChat.java:65) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec
9b]
        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
Caused by: java.lang.NullPointerException
        at vg.civcraft.mc.namelayer.GroupManager.getGroup(GroupManager.java:108) ~[?:?]
        at vg.civcraft.mc.citadel.command.commands.Fortification.execute(Fortification.java:52) ~[?:?]
        at vg.civcraft.mc.citadel.command.CommandHandler.execute(CommandHandler.java:56) ~[?:?]
        at vg.civcraft.mc.citadel.Citadel.onCommand(Citadel.java:119) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        ... 13 more

**Comment by ttk2** [comment]
I have already filed a similar but, but I think this is a different
command, I speculate its the default group feature not working properly, so
it looks to citadel like people are trying to run various commands without
any group arguments.

**Comment by jjj5311** [comment]
I think the pull I have out there will for sure fix this one, I am not sure
about the fortify issue now. I won't be able to test this until Monday
locally
