### ISSUE TITLE
Could not pass event BlockBreakEvent to Citadel v3.2.5

### ISSUE THREAD

**Issue by ttk2** [Civcraft/Citadel#81]
2015-03-14 13:43:07 [ERROR] Could not pass event BlockBreakEvent to Citadel v3.2.5
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.PlayerInteractManager.breakBlock(PlayerInteractManager.java:264) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.PlayerInteractManager.dig(PlayerInteractManager.java:164) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:552) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.PacketPlayInBlockDig.a(SourceFile:53) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.PacketPlayInBlockDig.handle(SourceFile:8) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
Caused by: java.lang.NullPointerException
        at vg.civcraft.mc.namelayer.permission.GroupPermission.isAccessible(GroupPermission.java:46) ~[?:?]
        at vg.civcraft.mc.citadel.reinforcement.PlayerReinforcement.isAccessible(PlayerReinforcement.java:57) ~[?:?]
        at vg.civcraft.mc.citadel.reinforcement.PlayerReinforcement.isAccessible(PlayerReinforcement.java:46) ~[?:?]
        at vg.civcraft.mc.citadel.listener.BlockListener.blockBreakEvent(BlockListener.java:165) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor100.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_75]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_75]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        ... 15 more

**Comment by rourke750** [comment]
How often is this?

**Comment by ttk2** [comment]
every few seconds when it was happening, non recently, probably a broken
reinforcement somewhere.

**Comment by suirad** [comment]
Please close.
Fixed here: https://github.com/Civcraft/NameLayer/commit/9b899253a9511b76f07f47c9ba226d0e29cab5fb
