### ISSUE TITLE
getReinforcement NPE during blockBreakEvent

### ISSUE THREAD

**Issue by erocs** [Civcraft/Citadel#84]
[ERROR] Could not pass event BlockBreakEvent to Citadel v3.2.5
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.PlayerInteractManager.breakBlock(PlayerInteractManager.java:264) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.PlayerInteractManager.a(PlayerInteractManager.java:192) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:565) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.PacketPlayInBlockDig.a(SourceFile:53) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.PacketPlayInBlockDig.handle(SourceFile:8) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
Caused by: java.lang.NullPointerException
        at vg.civcraft.mc.citadel.ReinforcementManager.getReinforcement(ReinforcementManager.java:114) ~[?:?]
        at vg.civcraft.mc.citadel.listener.BlockListener.blockBreakEvent(BlockListener.java:136) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor84.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_75]
        at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_75]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298) ~[spigot.jar:git-Spigot-1.7.9-R0.2-203-g02dec9b]
        ... 15 more

**Comment by rourke750** [comment]
Huh some how here: https://github.com/Civcraft/Citadel/blob/master/src/vg/civcraft/mc/citadel/listener/BlockListener.java#L135 it isnt finding the correct block event though it is confirmed to be there when isPlant() is called.  Are we running citadel build 103?

**Comment by WildWeazel** [comment]
Seems like this would happen whenever a plant is not where we would expect it to have grown. Naturally spawned cactus, for example, could be taller than expected. isPlant() doesn't guarantee anything about the blocks below it.

**Comment by ttk2** [comment]
yes 103 is live.

**Comment by jjj5311** [comment]
I think we just need to check if reinforcingBlock is null before passing to getReinforcement?

or should getReinforcement automatically return null if it is passed a null value?

**Comment by rourke750** [comment]
Yea that's all I'm going to do

**Comment by rourke750** [comment]
https://github.com/Civcraft/Citadel/commit/8436d86eed16f99ddcf3b41c5a54582b4b7af7c0

**Comment by rourke750** [comment]
@ttk2 new jar

**Comment by rourke750** [comment]
Tell me when its up

**Comment by ttk2** [comment]
its up.
