### ISSUE TITLE
2015-04-30 00:22:14 [WARN] java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.

### ISSUE THREAD

**Issue by ttk2** [Civcraft/Citadel#95]
2015-04-30 00:22:14 [WARN] java.lang.IllegalArgumentException: No enum constant org.bukkit.Material.§i§&§&§&§r§i§t§e§m§&§&§&§r§2§6§5§&§&§&§r§0§&§&§&§r§2§&§&§&§r§&§&§&§r§&§&§&§r
§0§&§&§&§r§&§&§&§r§&§&§&§r§&§&§&§r§&§&§&§r§r
2015-04-30 00:22:14 [WARN]      at java.lang.Enum.valueOf(Enum.java:236)
2015-04-30 00:22:14 [WARN]      at org.bukkit.Material.valueOf(Material.java:64)
2015-04-30 00:22:14 [WARN]      at vg.civcraft.mc.citadel.Utility.isDroppedReinforcementBlock(Utility.java:461)
2015-04-30 00:22:14 [WARN]      at vg.civcraft.mc.citadel.listener.BlockListener.onFortificationMode(BlockListener.java:85)
2015-04-30 00:22:14 [WARN]      at sun.reflect.GeneratedMethodAccessor233.invoke(Unknown Source)
2015-04-30 00:22:14 [WARN]      at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2015-04-30 00:22:14 [WARN]      at java.lang.reflect.Method.invoke(Method.java:606)
2015-04-30 00:22:14 [WARN]      at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:298)
2015-04-30 00:22:14 [WARN]      at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
2015-04-30 00:22:14 [WARN]      at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:502)
2015-04-30 00:22:14 [WARN]      at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:487)
2015-04-30 00:22:14 [WARN]      at org.bukkit.craftbukkit.v1_7_R4.event.CraftEventFactory.callBlockPlaceEvent(CraftEventFactory.java:148)
2015-04-30 00:22:14 [WARN]      at net.minecraft.server.v1_7_R4.ItemStack.placeItem(ItemStack.java:139)
2015-04-30 00:22:14 [WARN]      at net.minecraft.server.v1_7_R4.PlayerInteractManager.interact(PlayerInteractManager.java:391)
2015-04-30 00:22:14 [WARN]      at net.minecraft.server.v1_7_R4.PlayerConnection.a(PlayerConnection.java:662)
2015-04-30 00:22:14 [WARN]      at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.a(SourceFile:60)
2015-04-30 00:22:14 [WARN]      at net.minecraft.server.v1_7_R4.PacketPlayInBlockPlace.handle(SourceFile:9)
2015-04-30 00:22:14 [WARN]      at net.minecraft.server.v1_7_R4.NetworkManager.a(NetworkManager.java:184)
2015-04-30 00:22:14 [WARN]      at net.minecraft.server.v1_7_R4.ServerConnection.c(ServerConnection.java:81)
2015-04-30 00:22:14 [WARN]      at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:734)
2015-04-30 00:22:14 [WARN]      at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289)
2015-04-30 00:22:14 [WARN]      at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584)
2015-04-30 00:22:14 [WARN]      at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490)

**Comment by WildWeazel** [comment]
ok, why are we trying to parse item lore as a material...
https://github.com/Civcraft/Citadel/blob/master/src/vg/civcraft/mc/citadel/Utility.java#L461

**Comment by ttk2** [comment]
I blame rourke.

**Comment by rourke750** [comment]
Men. Need to remove the print log statement.  This isn't game breaking at all. Surprised it only showed up now.
