### ISSUE TITLE
Plans for 1.8?

### ISSUE THREAD

**Issue by Malvagio87** [Civcraft/Citadel#96]
Are there any plans to develop citadel for 1.8?

**Comment by ttk2** [comment]
its already got a working 1.8 version, you should just be able to grab it
from the jenkins dev branch.

**Comment by Malvagio87** [comment]
[15:02:13] [Server thread/INFO]: Starting minecraft server version 1.8.3
[15:02:13] [Server thread/INFO]: Loading properties
[15:02:13] [Server thread/INFO]: Default game type: SURVIVAL
[15:02:13] [Server thread/INFO]: This server is running CraftBukkit version git-Spigot-870264a-0a645a2 (MC: 1.8.3) (Implementing API version 1.8.3-R0.1-SNAPSHOT)
[15:02:13] [Server thread/INFO]: Server Ping Player Sample Count: 12
[15:02:13] [Server thread/INFO]: Using 4 threads for Netty based IO
[15:02:13] [Server thread/INFO]: Debug logging is disabled
[15:02:13] [Server thread/INFO]: Generating keypair
[15:02:13] [Server thread/INFO]: Starting Minecraft server on *:25565
[15:02:13] [Server thread/INFO]: Using epoll channel type
[15:02:13] [Server thread/INFO]: Set PluginClassLoader as parallel capable
[15:02:13] [Server thread/ERROR]: Could not load 'plugins/Citadel-3.2.8-40.jar' in folder 'plugins'
org.bukkit.plugin.UnknownDependencyException: NameLayer
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:219) [spigot.jar:git-Spigot-870264a-0a645a2]
	at org.bukkit.craftbukkit.v1_8_R2.CraftServer.loadPlugins(CraftServer.java:291) [spigot.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.DedicatedServer.init(DedicatedServer.java:199) [spigot.jar:git-Spigot-870264a-0a645a2]
	at net.minecraft.server.v1_8_R2.MinecraftServer.run(MinecraftServer.java:522) [spigot.jar:git-Spigot-870264a-0a645a2]
	at java.lang.Thread.run(Thread.java:745) [?:1.7.0_79]

I also get the same message when using the 1.8.0 spigot jar.  Is there a specific version i should be using?

**Comment by jjj5311** [comment]
Are you using namelayer? You have to run Namelayer with Citadel now to
handle UUIDs and ability to change names

**Comment by Malvagio87** [comment]
i am not, but will now

**Comment by ttk2** [comment]
that's been going on since 1.7.10 right? Eh good to try. You do know where
the build server is right?

**Comment by Malvagio87** [comment]
yea, i am on it now.. NameLayer 2.3.5-130?

**Comment by ttk2** [comment]
yup that's correct, groups are disabled by default you will need to go into
the config to enable them to use citadel, they are disabled by default
because servers use namelayer for just keeping names from changing.

**Comment by Malvagio87** [comment]
so namelayer prevents players from joining that change there name?

**Comment by Malvagio87** [comment]
so what exactly does namelayer do?

**Comment by rourke750** [comment]
@Malvagio87 Everything should be working.  It has not been through testing though.

**Comment by ttk2** [comment]
it keeps players from changing their name, Citadel needs it for group
functionality, I dont think there is a way to disable name keeping and
leave groups enabled but the other way around is explicitly supported.
